### ISSUE TITLE
Service down time during kubernetes scale up and down

### ISSUE THREAD

**Issue by JackQuincy** [Azure/ACS#10]
When scaling up or down an ACS Kubernetes cluster that has running services that are exposed publicly. Due to some contention between ACS and Kubernetes there is downtime for the publicly exposed services, my observations has been for about 3 mins during which new connections to the service will fail. This is a known issue with a known fix. I will update this issue with an ETA when it is known.

**Comment by JackQuincy** [comment]
ETA for the fix to be global is this friday 3/21.

**Comment by JackQuincy** [comment]
This fix is now rolled out globally

**Comment by stefanegg** [comment]
Thanks for fixing this. We experienced the same downtime for even longer periods (~10 mins) before this fix, now everything works smooth during both scale up and down.
