### ISSUE TITLE
Command `az acs kubernetes get-credentials` fails with error "The api-version '2017-07-01' is invalid."

### ISSUE THREAD

**Issue by sjdweb** [Azure/ACS#106]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Running `az acs kubernetes get-credentials --resource-group=$GROUP_NAME --name=$CLUSTER_NAME --ssh-key-file=./key` causes this error:

```
The api-version '2017-07-01' is invalid. The supported versions are '2018-01-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

```

**What you expected to happen**:
For it to set the correct credentials for given cluster.

**How to reproduce it** (as minimally and precisely as possible):
Launch above command.

**Anything else we need to know**:

**Comment by JackQuincy** [comment]
This is more of a cli bug and you might get more traction posting the issue there. @mboersma can you take a look?
