### ISSUE TITLE
kubectl exec fails connecting to windows container

### ISSUE THREAD

**Issue by SteveCurran** [Azure/ACS#108]
I am using ACS in Azure with the following command,

az acs create --orchestrator-type=kubernetes --resource-group testkubescale --name=testscale --agent-count=1 --generate-ssh-keys --windows --admin-username testing --admin-password password!

I deploy the container and container runs

I try kubectl exec -it podname powershell
Receive the following error.
"Error from server: error dialing backend: dial tcp 10.240.0.4:10250: getsockopt: connection timed out"

Cluster was working yesterday. I am in CentralUS.

**Comment by caseywatson** [comment]
Hi, Steve. How did you wind up resolving this?
