### ISSUE TITLE
How upgrade Kubernetes version to 1.8.x in ACS

### ISSUE THREAD

**Issue by krishna-dahifale** [Azure/ACS#109]
Hi,
**Orchestrator and version** : Kubernetes 1.7.7
**What you expected to happen**: Want upgrade kubernetes version from 1.7.7 to 1.8 & greater 
In AKS , We have az aks upgrade --kubernetes-version --name   --resource-group  [--no-wait]  [--yes] to do upgradation,which not  in case of ACS. 
Please suggest way to do so.....

**Comment by krishna-dahifale** [comment]
Any update??

**Comment by JackQuincy** [comment]
Upgrade is only supported in AKS. We have no plans to add it to ACS.

**Comment by Strandedpirate** [comment]
Is this the correct procedure for upgrading an k8s cluster created through the Azure portal?
https://github.com/Azure/acs-engine/tree/master/examples/k8s-upgrade
