### ISSUE TITLE
How do I upgrade a cluster in Azure ACS

### ISSUE THREAD

**Issue by nazneen84** [Azure/ACS#122]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-24T18:21:41Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.14", GitCommit:"9d72fafc46543ebdad024b7577012268bab543a7", GitTreeState:"clean", BuildDate:"2018-06-18T21:52:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:

I created a new cluster in my existing resource group like so:

$az acs create --name myname-k8s-cluster -g myname-k8s-rg --orchestrator-type Kubernetes --agent-count 3

Exported my kubeconfig

myname$ kubectl get nodes
No resources found.
Error from server (NotAcceptable): unknown (get nodes)

I realized my k8s client and server versions are incompatible so I tried upgrading the k8s server version to the latest

myname$ az resource list -g namalik-k8s-rg
[
  {
    "id": "/subscriptions/######/resourceGroups/myname-k8s-rg/providers/Microsoft.ContainerService/containerServices/myname-k8s-cluster",
    "identity": null,
    "kind": null,
    "location": "westus2",
    "managedBy": null,
    "name": "myname-k8s-cluster",
    "plan": null,
    "properties": null,
    "resourceGroup": "myname-k8s-rg",
    "sku": null,
    "tags": null,
    "type": "Microsoft.ContainerService/containerServices"
  }

etc

$az acs get-upgrades --name myname-k8s-cluster --resource-group myname-k8s-rg --output table
az acs: 'get-upgrades' is not in the 'az acs' command group. See 'az acs --help'.

**What you expected to happen**:

I would expect the acs commands work just like aks. I'd like to see upgrades available and be able to upgrade

**How to reproduce it** (as minimally and precisely as possible):

1. Install the client and server versions specified in the orchestrator version
2. $az login
3. $az acs kubernetes get-credentials --name myname-k8s-cluster -g myname-k8s-rg --file ./acs.conf
4. $export KUBECONFIG=./acs.conf
5. $az group create --name myname-k8s-rg --location westus2
6. $az acs create --name namalik-k8s-cluster -g namalik-k8s-rg --orchestrator-type Kubernetes --agent-count 3
7. $az acs get-upgrades --name myname-k8s-cluster --resource-group myname-k8s-rg --output table

I know I can downgrade the client version and continue using my cluster but I need to upgrade it at some point :)

**Comment by JackQuincy** [comment]
Upgrade is not a supported scenario on ACS. You'll either need to make a new cluster or manually upgrade the cluster, note manual upgrades will not be tracked by ACS so future ACS operation may not work as desired.
