### ISSUE TITLE
[enhancement] Find nearby stations

### ISSUE THREAD

**Issue by guysoft** [Azure/ACS#123]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** None

**Anything else we need to know**:
I want to build a kiosk that would display nearby buses in a given radius. For that I need a way to get GPS coordinates, and from them return a list of bus stations. Then I can pull them with curlbus.

The stations gps data is available [here](http://ftp://gtfs.mot.gov.il/israel-public-transportation.zip) and is updated daily. The reason I think this should be in curlbus is because its 177MB to download and update, and it seems an external service should do it, or at least an instance of curlbus (if you want your privacy).

**Comment by JackQuincy** [comment]
This appears to be unrelated the ACS infrastructure entirely and something that would live at the application layer. Did you mean to open this issue on curlbus?

**Comment by guysoft** [comment]
Ok, I have no idea how this ended up here. I don't even recall ever seeing this repository.
Anyway, sorry about that.
