### ISSUE TITLE
Kubernetes Cluster Federation

### ISSUE THREAD

**Issue by runemy** [Azure/ACS#15]
Hi. Is Kubernetes Cluster Federation (Ubernetes) something that fits into ACS future work?

Br. Rune

**Comment by JackQuincy** [comment]
@brendandburns @anhowe  I think this is possible today right? or is there more work remaining on us.

**Comment by brendandburns** [comment]
afaik, this should just work.

**Comment by runemy** [comment]
Thanks, good to know :) Would be nice to have some documentation/guideline on how to do this in Microsoft ACS, but I guess that is outside of this GitHub scope.
