### ISSUE TITLE
k8s clusters created shortly after GA with api version 2016-03-30 can't scale

### ISSUE THREAD

**Issue by JackQuincy** [Azure/ACS#16]
There is a bug in ACS that prevents older clusters from scaling. We are currently rolling out a fix with an ETA of friday 4/14 at the latest. Should be sooner.

**Comment by JackQuincy** [comment]
we have rolled out a fix for this globally. Error is unable to find resource ( should be network security group that isn't found). If someone runs into this again please reopen the issue

**Comment by moagarw** [comment]
I facing this error right now .. 

I want to change my cluster count from 6 to 3. 

My current cluster vm config is - Standard D4_v2.
K8s version - v1.6.6

I created this cluster around 2 weeks back.

This is the command i am using - az acs scale --name <cluster-name> --new-agent-count 3 --resource-group <resource_group>

Error thrown - 
{
, StatusMessage: \n {
  "error": {
    "code": "OperationNotAllowed",
    "target": "vmSize",
    "message": "Unable to perform Operation 'Update VM' on the VM because the requested size Standard_D2_v2 is not available in the cluster where the availability set is currently allocated. The available sizes are: Basic_A0,Basic_A1,Basic_A2,Basic_A3,Basic_A4,Standard_A0,Standard_A1,Standard_A2,Standard_A3,Standard_A4,Standard_A5,Standard_A6,Standard_A7,Standard_D1,Standard_D2,Standard_D3,Standard_D4,Standard_D11,Standard_D12,Standard_D13,Standard_D14,Standard_A1_v2,Standard_A2_v2,Standard_A4_v2,Standard_A8_v2,Standard_A2m_v2,Standard_A4m_v2,Standard_A8m_v2. Read more on VM resizing strategy at https://aka.ms/azure-resizevm."
  }
}

Even from Azure ACS UI it does not allow to change agent pool count. Same error is thrown.
