### ISSUE TITLE
The value 'Standard_NC6' of parameter 'agentProfile.vmSize' is not allowed

### ISSUE THREAD

**Issue by rutvijc** [Azure/ACS#17]
I'm trying to use the `Standard_NC6` VM type for my Kubernetes cluster using ACS. I've verified that my subscription has these VM types available. This is for the `eastus` region. However, I'm getting the aforementioned error when trying to bring up a Kubernetes cluster in ACS. Am I doing something wrong?

**Comment by amanohar** [comment]
@rutvijc, did you generate your template using the latest from ACS Engine? This size is now supported.

**Comment by rutvijc** [comment]
I'm using Azure CLI 2.0.2. Not sure if that answers the question.

**Comment by jpoon** [comment]
Try `az component update` maybe?

**Comment by rutvijc** [comment]
I was able to use ACS Engine successfully with the `Standard_NC6` vm size. Thanks.
