### ISSUE TITLE
Windows kubernetes clusters not working

### ISSUE THREAD

**Issue by JackQuincy** [Azure/ACS#25]
The image we were using was susceptible to Wanna Cry at deploy time. It would eventually run windows update and patch itself so existing clusters should be good, but the Windows team pulled the image down. We are working on a new build with a more recent version of windows and should start rolling it out by EOD, and by 6/2 we should have it globally available. We obviously need to be better about avoiding things like this in the future  before we GA this feature.
Existing clusters will no longer be able to scale up and down. To enable that feature a new cluster will need to be provisioned and brought up.

**Comment by JackQuincy** [comment]
We have started this deployment and are still on target for 6/2 EOD being rolled out globablly

**Comment by JackQuincy** [comment]
So we ran into issues in our deployment. My bad... Will be rolling out a working build as soon as we have one. ETA is sometime next week in prod.

**Comment by anhowe** [comment]
fixed week of June 2, 2017
