### ISSUE TITLE
Nginx-based Ingress Controller vs Azure Application Gateway

### ISSUE THREAD

**Issue by jamesbannan** [Azure/ACS#26]
I have a customer who is migrating the containers from AWS to Azure, and are looking to use Kubernetes on ACS.  They need SSL offloading and are wondering whether to use the Nginx-based Ingress Controller or the Azure Application Gateway. 

According to the Status of Kubernetes on ACS (https://github.com/Azure/ACS/blob/master/kubernetes-status.md#future-work) the Azure Ingress Controller will leverage the service-based Application Gateway, so they are wondering whether this is a better long-term strategy.

**Comment by sjdweb** [comment]
@jamesbannan Did you decide on this? Facing the same question.

**Comment by JackQuincy** [comment]
The ACS team doesn't take stances on which tech option to use because each use case has specific requirements.
