### ISSUE TITLE
Kubernetes Clusters Broken after Deployment or Unattended Upgrades

### ISSUE THREAD

**Issue by colemickens** [Azure/ACS#3]
## Problem

`docker 1.13.0` was released and seems to break outbound container->internet traffic. New clusters get the latest `docker` automatically. Existing clusters will install updates automatically and will be affected by this as the nodes reboot for whatever reason.

## Mitigation in ACS

The Azure Container Service is rolling out a fix that will pin `docker-engine` to `1.12.6` for the time being.

This change is already live in the open-source core of ACS, ACS-Engine. You can see that change here: https://github.com/Azure/acs-engine/pull/195

## Workaround for Existing Clusters

These steps should allow you to workaround this issue. Please note, if you blindly execute the following, it will reboot all of your worker nodes one-by-one with no delay. Please decompose these instructions and drain/cordon/upgrade your nodes if you can't handle all nodes being rebooted at once.

These steps will downgrade docker on all VMs and create an apt preference policy effectively pinning `docker-engine` to `1.12.*`.

```
# copy your SSH key to the master
scp ~/.ssh/id_rsa user@cluster.location.cloudapp.azure.com

# ssh to master
ssh user@cluster.location.cloudapp.azure.com

# workaround on all nodes (and reboot on all)
kubectl get nodes -o jsonpath={.items[*].metadata.name} \
    | tr ' ' '\n' \
    | grep -v master \
    | xargs -d '\n' -I "{}" \
        ssh -oStrictHostKeyChecking=no -i id_rsa {} bash -c "sudo apt-mark unhold docker-engine || true; \
            printf 'Package: docker-engine\nPin: version 1.12.*\nPin-Priority: 550\n' \
                | sudo tee /etc/apt/preferences.d/docker.pref; \
            sudo apt install -y --allow-downgrades docker-engine=1.12.6-0~ubuntu-xenial; \
            sudo nohup reboot &"

# workaround on master
sudo apt-mark unhold docker-engine || true; \
    printf 'Package: docker-engine\nPin: version 1.12.*\nPin-Priority: 550\n' \
        | sudo tee /etc/apt/preferences.d/docker.pref; \
    sudo apt install -y --allow-downgrades docker-engine=1.12.6-0~ubuntu-xenial; \
    sudo reboot
```

**Comment by anhowe** [comment]
This is now fixed and resolved.
