### ISSUE TITLE
no Container Service in azure portal after deploying kubernetes

### ISSUE THREAD

**Issue by Anmorata** [Azure/ACS#38]
hello,
I deployed the kubernetes cluster with acs-engine generated script, then deployed it (specified the cluster name ). when I logged into portal there is no azure container service, only master and agent nodes. when i do az acs show with specified name it says that cluster with that name doesn't exist. therefor I'm unable to use any az acs related commands. is it a bug or I'm doing anything wrong? double checked the service principal user and pass and they are correct

here is a template which i used in acs-engine
{
"apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.6.2",
      "kubernetesConfig": {
        "networkPolicy": "calico"
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "dnsprefix",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 1,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "user",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "servicePrincipalClientID": "",
      "servicePrincipalClientSecret": ""
    }
  }
}

**Comment by JackQuincy** [comment]
This is by design. If you deploy with ACS-Engine you are skipping using the ACS service so we can't store that data.
