### ISSUE TITLE
acs stops working

### ISSUE THREAD

**Issue by bialad** [Azure/ACS#41]
I've had this happen once before, but that time there were no errors. Just a unresponsive public endpoint and container creation failure. I try my best to find a reason to the failure, but both times I've ended up having to recreate the entire cluster.

This time I'm keeping the failed cluster running for debugging, but because of the cost of running two clusters I can't do that for long.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

Cluster public IP stops responding, and container creation fails. This is the only error message I can see.

```
MountVolume.SetUp failed for volume "kubernetes.io/secret/3036090c-6712-11e7-b20f-000d3a29b8df-default-token-2w2qk" (spec.Name: "default-token-2w2qk") pod "3036090c-6712-11e7-b20f-000d3a29b8df" (UID: "3036090c-6712-11e7-b20f-000d3a29b8df") with: mount failed: fork/exec /bin/mount: resource temporarily unavailable Mounting command: mount Mounting arguments: tmpfs /var/lib/kubelet/pods/3036090c-6712-11e7-b20f-000d3a29b8df/volumes/kubernetes.io~secret/default-token-2w2qk tmpfs [] Output:
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "brfportal"/"brfportal-auth-3849485180-4phdk". list of unattached/unmounted volumes=[default-token-2w2qk]
```

**Comment by colemickens** [comment]
Looks like some sort of resource exhaustion on the node where the pod was scheduled.

How saturated is your cluster/nodes?

`mount failed: fork/exec /bin/mount: resource temporarily unavailable`

**Comment by bialad** [comment]
I thought about that as well, but cpu and memory is well within limits.

As I remember the default-token is created with the cluster. Or am I mistaken?  What would cause mounting an existing resource to fail?

**Comment by JackQuincy** [comment]
This is surprising.  I know that newer versions of kubernetes have made updates here and I wonder if it goes away with that. We are updating the service currently and new clusters should get these improvments in the future. @rjtsdl can you ping here when we are deployed globally

**Comment by bialad** [comment]
It's always hard to say when an issue is resolved if it doesn't occur without a fix applied... But now I haven't seen it in a month, so I'm gonna close this and hope it doesn't come back.
