### ISSUE TITLE
Loadbalancer do not redirect traffic to k8s master

### ISSUE THREAD

**Issue by olblak** [Azure/ACS#42]
**Is this a BUG REPORT or FEATURE REQUEST?**:
I am not sure yet if it's a bug or a feature

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
I deployed a cluster with one master and one agent.
I then deploy a service with a public IP (Ingress).
I flagged the agent in 'maintenance mode' and migrate all pods on the master.

The loadbalancer continue to send the traffic to the agent (event if the agent was stopped) and didn't send traffics to the master

**What you expected to happen**:
I expect the loadbalancer to redirect traffic to the master as well.

**How to reproduce it** (as minimally and precisely as possible):

* Deploy a service with a public IP
* `kubectl cordon k8s-agent-********-0`
* `kubectl uncordon k8s-master-********-0` 
Loadbalancer should send traffic to k8s-master

**Anything else we need to know**:

I also noticed that by default, new master disable scheduling. 
Is it a good practice to avoid pods on the master?

**Comment by JackQuincy** [comment]
This is really an upstream issue. The Kubernetes cloud provider for azure is what makes this call. I believe this is by design. You could add the master vm from the portal. Though I'm not sure if the Kubernetes cloud provider will handle that properly/override it.

**Comment by djsly** [comment]
Technically the node should still take traffic even though is it cordoned no? And kube-proxy should redirect the traffic to the node to get to the pod.  

Could you share the output of the 
`kubectl describe service <service-name>`

As well as the status of the LB backend probe on the cordoned node ?

Thanks.
