### ISSUE TITLE
[HelpQuestion] about exposing a service on ACS 

### ISSUE THREAD

**Issue by vinayvenkat** [Azure/ACS#43]
**Is this a request for help?**:

When I execute the command to expose a service on ACS via: 
kubectl expose deployments nginx --port=80 --type=LoadBalancer

A load balancer automatically gets created, with right backend servers in the server pool etc. 

My question is how do the loadbalancers get instantiated and configured? Does this happen with the kubectl calling into the Azure CNI implementation which in turn instantiates the load balancer with the necessary configs? 
Thanks,
- Vinay
---

**Comment by JackQuincy** [comment]
The azure cloud provider running in the kubelet, calls into ARM and creates the load balancer etc with the right nics in the back end pool

**Comment by weinong** [comment]
closing the issue. please reopen if you have more questions.
