### ISSUE TITLE
Unable to re-deploy when agent pool uses managed disks

### ISSUE THREAD

**Issue by sjdweb** [Azure/ACS#62]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

We're using managed disks mainly for the disk encryption that comes for free and requires no key management.

The deployment template has various other things in them, and we tend to redeploy often - we may add a new subscription to a Azure Service Bus topic for example.

We're not even trying to scale the cluster in any way.

Currently this bug will block the deployment.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
```
Deployment failed. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "OperationNotAllowed",
        "message": "Scaling a cluster with an agent pool(s) with managed disks is unsupported"
      }
    ]
  }
}
```

**What you expected to happen**:
If we're not trying to scale the agent pool (as the error says) - the deployment should pass.

**How to reproduce it** (as minimally and precisely as possible):
Deploy a new azure cluster service with managed disks for your agent pool. Immediately re-deploy, you'll see the error.

**Anything else we need to know**:
No.

**Comment by rjtsdl** [comment]
@sjdweb thanks for reporting. we are tracking this.

**Comment by rjtsdl** [comment]
@sjdweb wondering how do you do the deployment? Can you give detail steps?

When you say, you will need to `add a new subscription to a Azure Service Bus topic`. Do you actually change the ARM template?

**Comment by rjtsdl** [comment]
I tried using az cli to re-deploy right after the initial deployment succeed. It doesn't throw any error. I guess, there is some change in your `re-deploy`, which get the 're-deploy' is classified as an update on the existing cluster. 

Note, we don't support any update scenario except for scaling. For managed disks agents, apparently, we don't support any kind update for now.

**Comment by JackQuincy** [comment]
On a side note ACS-Engine now supports scaling down with managed disks so we can just remove our check and start supporting it as well.

**Comment by rjtsdl** [comment]
@JackQuincy , how about scaling up with managed disks?

**Comment by JackQuincy** [comment]
Yes, that was always supported.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sjdweb** [comment]
@rjtsdl Hi, thanks for getting back. I can consistently reproduce the error by redeploying the ARM template with no changes, straight after an initial deployment.

Has there been an update recently? I am running `azure-cli` 2.0.14 and deploying to `UkSouth`.

> When you say, you will need to add a new subscription to a Azure Service Bus topic. Do you actually change the ARM template?
Yes, to the Service Bus section of resources - this is the reason behind needing to redeploy, but I see the error even without any change to the ARM file.

**Comment by rjtsdl** [comment]
@sjdweb , as @JackQuincy pointed out, we are going to remove the scaling gate for managedDisks agent with k8s. I will update this thread later.

**Comment by sjdweb** [comment]
hi @rjtsdl was this resolved? *seems* to be working as of today.

**Comment by weinong** [comment]
yes it is. Closing the issue.
