### ISSUE TITLE
Enable RBAC in kubernetes orchestration

### ISSUE THREAD

**Issue by mfaizanse** [Azure/ACS#65]
**Is this a request for help?**:
HELP
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

I have deployed a kubernetes cluster (linux) using azure container service. I was trying to deploy prometheus-operator but found that RBAC is not enabled. 

Is there any was enable RBAC in acs?

My query is that when will be RBAC supported in acs? I saw that ace-engine repository worked on RBAC in july but its not added to acs till now, How much time its takes for the new upgrades in ace-engine to appear in acs? And any timeline for kubernetes 1.7.x upgrade?

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes : 1.6.6

**What happened**:
Unable to create clusterrolebindings and unable to deploy prometheus-operator.

**What you expected to happen**:
Clusterrolebindings should be created.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by weinong** [comment]
It is under our backlog. 
@anhowe @sauryadas

**Comment by markwaldkat** [comment]
Any news about this?
Is it also taken into account for AKS?

**Comment by mfaizanse** [comment]
Yes, RBAC is working aks with k8s 1.8.1. Not sure about ACS.

**Comment by sauryadas** [comment]
No plan to fix this in ACS

**Comment by kingdonb** [comment]
Excellent.  I was just searching for how to disable it
