### ISSUE TITLE
exposing with sessionAffinity is not respected

### ISSUE THREAD

**Issue by slabber** [Azure/ACS#7]
I created a new nginx deployment using:
`kubectl run my-nginx --image=nginx --port 80`

Then expose it using:
`kubectl expose deployment my-nginx --port=80 --type=LoadBalancer --session-affinity=ClientIP`

But when I look at the options set in the LB in Azure the 'Session persistence' is set to 'None'.

Shouldn't this be 'ClientIP'?

**Comment by wilsondy** [comment]
+1.  (You can set it manually in the Portal after creation)

Also fails with Services defined with a LoadBalancer and ClientIP affinity in their spec.

**Comment by JackQuincy** [comment]
@colemickens to make sure he has seen this

**Comment by colemickens** [comment]
This is fixed in the latest release. I added support for plumbing that preference into the Azure LB. Someone else back ported, so it should be available in new ACS clusters running 1.6.6 or greater.

**Comment by jpoon** [comment]
Yep. Supported as of v1.6.5.

Initial fix into 1.7: https://github.com/kubernetes/kubernetes/pull/45523
Backport: https://github.com/kubernetes/kubernetes/pull/46174
