### ISSUE TITLE
Broken dashboard in Kubernetes cluster 1.7.7

### ISSUE THREAD

**Issue by AlexeyAtIgloo** [Azure/ACS#70]
**Is this a request for help?**:
---
yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

```
Client Version: v1.8.0
Server Version: v1.7.7
```
`azure-cli (2.0.18)`

**What happened**:

- Created new Kubernetes cluster of the api-version=2017-07-01 
- Obtains kube config
- Started kubectl proxy
- Tried accessing ui dashboard

RESULT: 
Unable to access dashboard at:
http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
assets are failing to load with 404
```
proxy	200	document	Other	1.1 KB	98 ms
vendor.9aa0b786.css	404	stylesheet	proxy	116 B	218 ms
app.8ebf2901.css	404	stylesheet	proxy	116 B	217 ms
vendor.840e639c.js	404	script	proxy	116 B	218 ms
appConfig.json	404	script	proxy	116 B	217 ms
app.68d2caa2.js	404	script	proxy	116 B	217 ms
appConfig.json	404	script	proxy	116 B	71 ms
app.68d2caa2.js	404	script	proxy	116 B	72 ms
GET http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/static/app.8ebf2901.css net::ERR_ABORTED
GET http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/static/vendor.9aa0b786.css net::ERR_ABORTED
GET http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/api/appConfig.json net::ERR_ABORTED
GET http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/static/app.68d2caa2.js net::ERR_ABORTED
GET http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/static/vendor.840e639c.js net::ERR_ABORTED
GET http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/api/appConfig.json net::ERR_ABORTED
GET http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/static/app.68d2caa2.js net::ERR_ABORTED
```

or (new access method since 1.7):
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy

where i'm getting:
```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://10.244.3.2:9090/'
```

**What you expected to happen**:
I'm aware and RBAC is permissions model is now enabled, but there seems to be clusterrolebinding kubernetes-dashboard, so that should open it up.

**How to reproduce it** (as minimally and precisely as possible):
```
export CLUSTERNAME=dev0test0cluster123
az group create --name $CLUSTERNAME --location westus2
az acs create --orchestrator-type kubernetes --resource-group $CLUSTERNAME --name $CLUSTERNAME --master-count 3 --agent-count 3 --ssh-key-value <sensitive> --api-version 2017-07-01
```
...wait for VMs and system pods to start
```
az acs kubernetes get-credentials -n $CLUSTERNAME -g $CLUSTERNAME --file ~/.kube/config
kubectl proxy
```

Now try to access dashboard via any of the below urls.:
[http://localhost:8001/ui](http://localhost:8001/ui)

[http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy](http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy)

**Anything else we need to know**:
Following image in listed on dashboard deployment:
`image: gcrio.azureedge.net/google_containers/kubernetes-dashboard-amd64:v1.6.3`

Also nothing interesting in logs of the dashboard pod:
```
Using HTTP port: 8443
Using in-cluster config to connect to apiserver
Using service account token for csrf signing
No request provided. Skipping authorization header
Successful initial request to the apiserver, version: v1.7.7
No request provided. Skipping authorization header
Creating in-cluster Heapster client
Successful initial request to heapster
```

**Comment by tiagorosendo** [comment]
try put / after proxy, this work to me

**Comment by oriyastyle** [comment]
I am experiencing the same issue and putting / after proxy did not resolve the error. Kubectl client version is 1.8.1 and server version is 1.7.7. Any other suggestions?

**Comment by oriyastyle** [comment]
Update - not sure why but the dashboard worked this morning once you put / after proxy.

**Comment by AlexeyAtIgloo** [comment]
@tiagorosendo Yep that did it, but interestingly `http://localhost:8001/ui` use to redirect to:
`http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/`
(just tested on latest version on minikube)

now it does not add `/` at the end of URL.
redirect from `http://localhost:8001/ui/`works fine.

Is that a misconfiguration of api-server or new behaviour?

**Comment by doggy8088** [comment]
@AlexeyAtIgloo I got the same issue just exactly like you.

@tiagorosendo What do you mean **_try put / after proxy_**?

**Comment by AlexeyAtIgloo** [comment]
@doggy8088 try this `http://localhost:8001/ui/` or that `http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/` url (assuming you are doing `kubectl proxy`)

**Comment by doggy8088** [comment]
@AlexeyAtIgloo Yes, I do put slash ( / ) in end of this url.  The problem is still exist.

**Comment by doggy8088** [comment]
I also tried on creating ACS for Windows Containers.  Same issue.  K8S Web UI unable to be shown correctly.

Here are the steps to reproduce this problem:

1. `az group create -n K8SDemoACS7 -l eastus2`
2. `az acs create -t kubernetes -g K8SDemoACS7 -l eastus2 -n myK8sCluster7 --agent-count=1 --windows --admin-username azueruser --admin-password Password1234 > acs_k8s_create.log`
3. `az acs kubernetes get-credentials --resource-group=K8SDemoACS7 --name=myK8sCluster7`
4. `az acs kubernetes browse --resource-group=K8SDemoACS7 --name=myK8sCluster7`

Then open http://localhost:8001/ui/ using any browser.

**Comment by JiangtianLi** [comment]
@AlexeyAtIgloo  Does your cluster have Windows agent node or it is a Linux cluster only?

**Comment by doggy8088** [comment]
@JiangtianLi Due to his command: `az acs create --orchestrator-type kubernetes --resource-group $CLUSTERNAME --name $CLUSTERNAME --master-count 3 --agent-count 3 --ssh-key-value <sensitive> --api-version 2017-07-01`.  That is a Linux agent node only.

**Comment by JiangtianLi** [comment]
@doggy8088  Thanks. That's what I thought. I was told that on a yammer thread, it mentioned the issue is about Windows. So just curious.

**Comment by JackQuincy** [comment]
I tried this with a 1.7.5 cluster just barely
calls that worked:
http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy 
http://localhost:8001/ui
I got the same error as the original poster on 
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy

that error might be related to azure docker sending large packets. Not sure. Side note I am on an old version of kubectl 1.5.3

**Comment by ams0** [comment]
All of a sudden my dashboard is back. I didn't do anything, really, just wait it out. Before (i.e. about 12 hours ago), I got this error:
```
$ curl http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
 <!doctype html> <html ng-app="kubernetesDashboard"> <head> <meta charset="utf-8"> <title ng-controller="kdTitle as $ctrl" ng-bind="$ctrl.title()"></title> <link rel="icon" type="image/png" href="assets/images/kubernetes-logo.png"> <meta name="viewport" content="width=device-width"> <link rel="stylesheet" href="static/vendor.9aa0b786.css"> <link rel="stylesheet" href="static/app.8ebf2901.css"> </head> <body> <!--[if lt IE 10]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser.
      Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your
      experience.</p>
    <![endif]--> <kd-chrome layout="column" layout-fill=""> </kd-chrome> <script src="static/vendor.840e639c.js"></script> <script src="api/appConfig.json"></script> <script src="static/app.68d2caa2.js"></script> </body> </html>
```

And just now, same cluster, same browser, works fine.

**Comment by AlexeyAtIgloo** [comment]
@ams0 I don't think thats an error, thats a standard response to the curl client. I get same output on a working dashboard.

```
curl http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
 <!doctype html> <html ng-app="kubernetesDashboard"> <head> <meta charset="utf-8"> <title ng-controller="kdTitle as $ctrl" ng-bind="$ctrl.title()"></title> <link rel="icon" type="image/png" href="assets/images/kubernetes-logo.png"> <meta name="viewport" content="width=device-width"> <link rel="stylesheet" href="static/vendor.9aa0b786.css"> <link rel="stylesheet" href="static/app.8ebf2901.css"> </head> <body> <!--[if lt IE 10]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser.
      Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your
      experience.</p>
    <![endif]--> <kd-chrome layout="column" layout-fill=""> </kd-chrome> <script src="static/vendor.840e639c.js"></script> <script src="api/appConfig.json"></script> <script src="static/app.68d2caa2.js"></script> </body> </html>
```

**Comment by doggy8088** [comment]
Neither http://localhost:8001/ui nor http://localhost:8001/ui/ works.

I finally realized that it will work if you append a slash ( / ) after the `http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy` url which the RIGHT url will be `http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/` and all the problem will gone. 😢

**Comment by AlexeyAtIgloo** [comment]
As we have a workaround with a slash at the end, I don't mind closing this as it is nothing major.

**Comment by doggy8088** [comment]
It's already an known issue [here](https://github.com/kubernetes/kubernetes/issues/52729) and been listed on [kubernetes/dashboard](https://github.com/kubernetes/dashboard)'s FAQ here: [I am seeing 404 errors when trying to access Dashbord. Dashboard resources can not be loaded.](https://github.com/kubernetes/dashboard/wiki/FAQ#i-am-seeing-404-errors-when-trying-to-access-dashbord-dashboard-resources-can-not-be-loaded)

**Comment by doggy8088** [comment]
@AlexeyAtIgloo I think you can close this issue on your own.

**Comment by AlexeyAtIgloo** [comment]
@doggy8088 thanks for references. Closing it as it should be fixed in future API server.
