### ISSUE TITLE
The VM Size of Master is not allowed in your subscription

### ISSUE THREAD

**Issue by Anmorata** [Azure/ACS#74]
I'm trying to install kubernetes on azure with az cli, but I get the error:

```
Deployment failed. {
  "error": {
    "code": "BadRequest",
    "message": "The VM Size of Master is not allowed in your subscription in location 'westeurope'. Master VM Size 'Standard_D2' is available in locations: eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth. "
  }
}
```

I tried to install from web, but I get the same error there. as I know there is no way to choose master vm size (the only way is with acs-engine).

**Comment by AlexeyAtIgloo** [comment]
Same here. Tried portal and cli, looks like it is unusable region at the moment.

**Comment by rjtsdl** [comment]
@Anmorata  @AlexeyAtIgloo ,

WestEurope was suffering Standard_D2 exhaustion. We have switched the default master vm size to Standard_D2_v2. Can you retry, see if the problem still there?

**Comment by Anmorata** [comment]
yes its fixed

**Comment by luhkevin** [comment]
I'm getting something similar, but with westus2:
`The VM size of Master is not allowed in your subscription in location 'westus2'`
What's the deal here?

**Comment by JackQuincy** [comment]
@luhkevin That looks like your subscription doesn't have access to the vmsize that is being requested for the masters. In west us2 you can select your master size. I'm actually not familiar with how to request having a size be added to your subscription in the given region. @dmitsh  @weinong do either of you know how to make a request for access to new vm sizes?

**Comment by luhkevin** [comment]
Hmm, here is the rest of the error message:
```
'Standard_D2_v2' is available in locations: brazilsouth,canadacentral,centralus,centraluseuap,eastus,eastus2,eastus2euap,japaneast,southcentralus,southeastasia,southindia,westeurope."
```

To clarify, I have to explicitly add the 'Standard_D2_v2' vm size to my westus2 region?

**Comment by mayankvaish7** [comment]
You guys are having "Resource group" in the region where master size is exhausted/not available.

Solution create the new resource group altogether in --  brazilsouth,canadacentral,centralus,centraluseuap,eastus,eastus2,eastus2euap,japaneast,southcentralus,southeastasia,southindia,westeurope""

under the step 1 itself. which will solve the problem.

Problem is you can't have resource group belonging to USWEST2(exhausted master VM of size dv2) and then mention in Step1 that use CanadaCentral for VMs. It is Bad request because you should have Resourcegroup ITSELF which belongs to appropriate region , which does not have Vm exhausted of particular size.

**Comment by alexeyzimarev** [comment]
The issue is that the [Quick Start guide](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough) tell us to create a resource group in eastus, westeurope, centralus, canadacentral, canadaeast. This clearly includes westeurope. But if I create a resource group in westeurope, I cannot get the aks created with error message:

> Details: The VM size of Agent is not allowed in your subscription in location 'westeurope'. Agent VM size 'Standard_DS1_v2' is available in locations: australiaeast,australiasoutheast,brazilsouth,canadacentral,canadaeast,centralindia,centralus,centraluseuap,eastasia,eastus,eastus2,eastus2euap,japaneast,japanwest,koreacentral,koreasouth,northcentralus,northeurope,southcentralus,southindia,uksouth,ukwest,westcentralus,westindia,westus,westus2

**Comment by mebrein** [comment]
This issue doesn't seem to be solved at all. Query `az vm list-sizes -l westeurope --output table` returns 'Standard_F2s_v2'. When I try to use it with az aks create, I get the error that the VM size of Agent is not allowed. Tried also other sizes like DS2_v2, etc,, same problem.

**Comment by mayankvaish7** [comment]
Your "Resourcegroup" has to be in " eastus, westeurope, centralus,
canadacentral, canadaeast". Because of discrepancy this error is coming.

Mayank Vaish
Ph : 801-706-3261(Cell)

**Comment by alexvicegrab** [comment]
I have the same issue, displayed when trying to create an aks cluster

**Comment by amerzouq** [comment]
i have the same probelm my ressource group is in westeurope

az aks create -g name -n name --node-count 5 --node-vm-size Standard_D2_v2

Operation failed with status: 'Bad Request'. Details: The VM size of Agent is not allowed in your subscription in location 'westeurope'. Agent VM size 'Standard_D2_v2' is available in locations: australiaeast,australiasoutheast,brazilsouth,canadacentral,canadaeast,centralindia,centralus,centraluseuap,eastasia,eastus,eastus2euap,japaneast,japanwest,koreasouth,northcentralus,northeurope,southcentralus,southindia,uksouth,ukwest,westindia,westus,westus2.

**Comment by rafaelfbs** [comment]
@rjtsdl

The same happens in brazilsouth. I tried to set master vmSize param, but nothing changed.

> The VM Size of Master is not allowed in your subscription in location 'brazilsouth'. Master VM Size
> 'Standard_D2_v2' is available in locations: eastus, eastus2, westus, centralus, northcentralus, southcentralus,
> northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast.

**Comment by shubhasismathur** [comment]
I used eastus as region and followed the official documentation of Azure AKS, strange it gives me the same error.

Operation failed with status: 'Bad Request'. Details: The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'eastus'. The available VM sizes are Standard_D16_v3,Standard_D16a_v4,Standard_D16as_v4,Standard_D16s_v3,Standard_D2_v3,Standard_D2a_v4,Standard_D2as_v4,Standard_D2s_v3,Standard_D32_v3,Standard_D32a_v4,Standard_D32as_v4,Standard_D32s_v3,Standard_D48_v3,Standard_D48a_v4,Standard_D48as_v4,Standard_D48s_v3,Standard_D4_v3,Standard_D4a_v4,Standard_D4as_v4,Standard_D4s_v3,Standard_D64_v3,Standard_D64a_v4,Standard_D64as_v4,Standard_D64s_v3,Standard_D8_v3,Standard_D8a_v4,Standard_D8as_v4,Standard_D8s_v3,Standard_D96a_v4,Standard_D96as_v4,Standard_E16_v3,Standard_E16a_v4,Standard_E16as_v4,Standard_E16s_v3,Standard_E20a_v4,Standard_E20as_v4,Standard_E2_v3,Standard_E2a_v4,Standard_E2as_v4,Standard_E2s_v3,Standard_E32-16s_v3,Standard_E32-8s_v3,Standard_E32_v3,Standard_E32a_v4,Standard_E32as_v4,Standard_E32s_v3,Standard_E48_v3,Standard_E48a_v4,Standard_E48as_v4,Standard_E48s_v3,Standard_E4_v3,Standard_E4a_v4,Standard_E4as_v4,Standard_E4s_v3,Standard_E64-16s_v3,Standard_E64-32s_v3,Standard_E64_v3,Standard_E64a_v4,Standard_E64as_v4,Standard_E64i_v3,Standard_E64is_v3,Standard_E64s_v3,Standard_E8_v3,Standard_E8a_v4,Standard_E8as_v4,Standard_E8s_v3,Standard_E96a_v4,Standard_E96as_v4,Standard_F16s_v2,Standard_F2s_v2,Standard_F32s_v2,Standard_F48s_v2,Standard_F4s_v2,Standard_F64s_v2,Standard_F72s_v2,Standard_F8s_v2,Standard_H16,Standard_H16m,Standard_H16mr,Standard_H16r,Standard_H8,Standard_H8m,Standard_L16s_v2,Standard_L32s_v2,Standard_L48s_v2,Standard_L64s_v2,Standard_L80s_v2,Standard_L8s_v2,Standard_M128,Standard_M128-32ms,Standard_M128-64ms,Standard_M128m,Standard_M128ms,Standard_M128s,Standard_M16-4ms,Standard_M16-8ms,Standard_M16ms,Standard_M208ms_v2,Standard_M208s_v2,Standard_M32-16ms,Standard_M32-8ms,Standard_M32ls,Standard_M32ms,Standard_M32ts,Standard_M64,Standard_M64-16ms,Standard_M64-32ms,Standard_M64ls,Standard_M64m,Standard_M64ms,Standard_M64s,Standard_M8-2ms,Standard_M8-4ms,Standard_M8ms,Standard_NC12_Promo,Standard_NC12s_v2,Standard_NC24_Promo,Standard_NC24r_Promo,Standard_NC24rs_v2,Standard_NC24s_v2,Standard_NC6_Promo,Standard_NC6s_v2,Standard_ND12s,Standard_ND24rs,Standard_ND24s,Standard_ND6s,Standard_NV12_Promo,Standard_NV24_Promo For more details, please visit https://aka.ms/cpu-quota

**Comment by soorajSpowers4u** [comment]
how to add the prefered VM size in "az aks create" command ??? Im using a free tier account and im trying to deploy an aks cluster

**Comment by shubham1172** [comment]
> how to add the prefered VM size in "az aks create" command ??? Im using a free tier account and im trying to deploy an aks cluster

See `--node-vm-size` in https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create
E.g., `az aks create <other flags> --node-vm-size DS3_v2`

Make sure that you are selecting a compatible size. The easiest way is to find one from the portal when you are creating the AKS cluster manually.
