### ISSUE TITLE
Windows agents scaling throwing error: Changing property 'agentPoolProfile.OSType' is not allowed.

### ISSUE THREAD

**Issue by doggy8088** [Azure/ACS#76]
**Is this a request for help?**:
Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Unable to change `new-agent-count`

**What you expected to happen**:
Able to change agent count

**How to reproduce it** (as minimally and precisely as possible):
1. `az group create -n K8SDemoACS -l canadacentral`
2. `az acs create -t kubernetes --orchestrator-release=1.6 -g K8SDemoACS -l canadacentral -n k8scluster1 --agent-count=2 --windows --admin-username <username> --admin-password <password>`
3. `az acs scale -g K8SDemoACS -n k8scluster1 --new-agent-count 3`

Then you will get the following error:

```
An error has occurred in subscription 6d2fcc60-715d-41ab-a5f2-6923c826436d, resourceGroup: K8SDemoACS request: Provisioning of resource(s) for container service k8scluster1 in resource group K8SDemoACS failed. Message: {
  "code": "PropertyChangeNotAllowed",
  "message": "Changing property 'agentPoolProfile.OSType' is not allowed.",
  "target": "agentPoolProfile.OSType"
 }. Details: .
```

**Anything else we need to know**:
How can I assign a new agent count by using Azure CLI 2.0?

**Comment by JackQuincy** [comment]
This appears to be a service bug. I believe it only affects windows clusters. I'll look into what is happening here

**Comment by JackQuincy** [comment]
This was caused by an issue in the swagger for ACS. It should be fixed now if you use the [latest](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.0.20) az cli or cloud shell.

**Comment by doggy8088** [comment]
@JackQuincy The latest az cli doesn't works.  See the log:

```
C:\Projects
$ az acs scale -g K8SDemoACS -n k8scluster1 --new-agent-count 4
An error has occurred in subscription 6d2fcc60-715d-41ab-a5f2-6923c826436d, resourceGroup: K8SDemoACS request: Provisioning of resource(s) for container service k8scluster1 in resource group K8SDemoACS failed. Message: {
  "code": "PropertyChangeNotAllowed",
  "message": "Changing property 'agentPoolProfile.OSType' is not allowed.",
  "target": "agentPoolProfile.OSType"
 }. Details: .

C:\Projects
$ az --version
azure-cli (2.0.20)
```

**Comment by doggy8088** [comment]
@JackQuincy The problem is confim solved. Thanks.
