### ISSUE TITLE
Swarm Mode & latest docker version

### ISSUE THREAD

**Issue by vishal-biyani** [Azure/ACS#79]
**Is this a request for help?**: Yes
The ACS currently only supports Docker Swarm at Docker version lower than 1.12. After 1.12, Swarm mode was introduced which brings a lot of changes. ATM ACS does not support latest Docker version and Swarm mode (One can run it in ACS-Engine with a template). Is there any plan in near future to introduce the current version of Docker and Swarm in ACS umbrella? 

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Swarm

**Comment by JackQuincy** [comment]
ACS supports swarm mode in these regions
UK West
UK South
West Central US
West US 2
Canada East
Canada Central
West India
South India
Central India
The orchestrator name is DockerCE. Try one of those regions with that orchestrator and let me know if it works for you.

**Comment by vishal-biyani** [comment]
Thanks @JackQuincy I will try out and let you know if I run into any issues.

**Comment by vishal-biyani** [comment]
@JackQuincy , Does ACS REST APIs accept 'DockerCE' as orchestrator  type? 
I get `request: OrchestratorType has unknown orchestrator: DockerCE` response for bellow payload.

```
Payload: {
    "location": "ukwest",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "DockerCE"
        },
        "masterProfile": {
            "count": "1",
            "fqdn": "swarmmaster",
            "dnsPrefix": "swarmmaster"
        },
        "agentPoolProfiles": [
            {
                "name": "swarmagent",
                "count": "1",
                "vmSize": "Standard_D2",
                "dnsPrefix": "swarmagent"
            }
        ],
        "linuxProfile": {
            "adminUsername": "vbiyani",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": "ssh-rsa ********"
                    }
                ]
            }
        }
    }
}
```

**Comment by JackQuincy** [comment]
It depends on the api version. 2017-07-01 supports dockerCE. 2017-01-31 actually supports SwarmMode  named as it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vishal-biyani** [comment]
Thanks a lot, @JackQuincy appreciate the prompt responses. I will close this issue.
