### ISSUE TITLE
ACS/AKS relationship + roadmaps

### ISSUE THREAD

**Issue by colemickens** [Azure/ACS#80]
(As this is a meta question, neither a feature request nor issue, I'm forgoing the template...)

There were some questions about this in `#sig-azure` and I had my own questions as I was kicking the tires today. In general, I'm hoping that the ACS/AKS team(s) can document the answers to these questions and/or generally highlight the expected roadmaps for ACS and AKS.

Questions:

* Will ACS and AKS continue to co-exist?
* Is ACS deprecated? If so, does this mean generally DC/OS and Swarm are going to be deprecated in Azure (other than where supported directly by Mesosphere and Docker Inc).
* Do enhancements to ACS-Engine directly flow to AKS, or no? It seems (per a Twitter thread?) that AKS is still missing some things enabled in ACS-Engine - its unclear if it's just not wired up or if AKS is a separate code effort entirely.

**Comment by rocketraman** [comment]
Relevant link: https://azure.microsoft.com/en-us/blog/introducing-azure-container-service-aks-managed-kubernetes-and-azure-container-registry-geo-replication/

**Comment by Preskton** [comment]
Very interested in feedback here, as we have spent considerable effort and brainpower toward making ACS work for our deployments.

**Comment by zimmertr** [comment]
I am also interested in this. I posted this question in #sig-azure a few days ago and didn't get a huge response from the dev team.

**Comment by sauryadas** [comment]
Answers inline-

1. Will ACS and AKS continue to co-exist?
    Yes for the time being. ACS is a GA service while AKS is a preview service. When they reach parity we will revisit this topic.

2. Is ACS deprecated? If so, does this mean generally DC/OS and Swarm are going to be deprecated in Azure (other than where supported directly by Mesosphere and Docker Inc).
    ACS is not deprecated. We are looking at making DC/OS and Swarm available only through the Azure marketplace where they have always been available. 

3. Do enhancements to ACS-Engine directly flow to AKS, or no? It seems (per a Twitter thread?) that AKS is still missing some things enabled in ACS-Engine - its unclear if it's just not wired up or if AKS is a separate code effort entirely.
     A decision on this has not been made yet.

**Comment by zimmertr** [comment]
https://www.reddit.com/r/AZURE/comments/7d7diz/ama_aks_managed_kubernetes_on_azure

**Comment by cloudmelon** [comment]
I attended a workshop in MS, they explained that Kubernetes is winning among all other orchestrators,  why AKS will also become the winner as a perfect implementation of managed Kubernetes in Azure. I think that will explain everything. 

https://azure.microsoft.com/en-us/blog/introducing-azure-container-service-aks-managed-kubernetes-and-azure-container-registry-geo-replication/
