### ISSUE TITLE
Kubernetes dashboard not showing with kubectl proxy or az acs kubernetes browse

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/ACS#86]
**Is this a request for help?**: 
Yes

**Orchestrator and version**: 
Kubernetes v1.7.7

**What happened**:
I installed a acs k8s cluster. When I try to proxy the dashboard locally (with kubectl or az acs kubernetes browse) it opens th browser with http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy, but it only shows a blank screen. 

**What you expected to happen**:
See the kubernetes dashboard

**How to reproduce it** (as minimally and precisely as possible):
Install a new acs cluster
Get the credentials (kube config file)
Try to proxy/ browse the dashboard

**Comment by jmalobicky** [comment]
@bramvdklinkenberg, I noticed the same issue with ACS 1.7.7. I thought it was browser cache but clearing had no impact. I was able to find this URL to work - http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/

**Comment by ermontgo** [comment]
This would be fantastic to get fixed and would help my team a lot

**Comment by davidobrien1985** [comment]
Just got the same error with a brand new ACS cluster.

Browsing to http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/ worked for me as well.

**Comment by jmeijrink** [comment]
I have the same issue, all static content seems to be missing.
![image](https://user-images.githubusercontent.com/788844/36153276-0ce426fc-10ce-11e8-9804-ef21b52290f2.png)

**Comment by jmeijrink** [comment]
I fixed the issue on my machine, due to following post:
https://github.com/kubernetes/dashboard/wiki/FAQ#i-am-seeing-404-errors-when-trying-to-access-dashbord-dashboard-resources-can-not-be-loaded

mentioned in https://github.com/kubernetes/dashboard/issues/2368

Summary: add a trailing /

**Comment by bramvdklinkenberg** [comment]
If you use the az cli to proxy the dashboard it works fine (plus opens a browser automatically)

**Comment by bramvdklinkenberg** [comment]
Use http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
